<a href="https://colab.research.google.com/github/Puneeth0094/AI/blob/main/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
#import the libraries

In [9]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [10]:
tf.__version__

'2.4.0'

In [11]:
#Part-1 Data Pre-processing

In [12]:
dataset=pd.read_csv("Churn_Modelling.csv")
dataset.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [13]:
X=dataset.iloc[:,3:-1].values
y=dataset.iloc[:,-1].values

In [14]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [15]:
print(y)

[1 0 1 ... 1 1 0]


In [16]:
#Encoding categorical data

In [17]:
#label encoding for Gender column

In [18]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X[:, 2]=le.fit_transform(X[:, 2])

In [19]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [20]:
#one hot encoding for Geography column

In [21]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[("encoder",OneHotEncoder(),[1])],remainder="passthrough")
X=np.array(ct.fit_transform(X))

In [22]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [24]:
#Splitting the dataset into the Training set and Test set

In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)


In [26]:
#Feature Scaling

In [27]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)


In [28]:
print(X_train)

[[-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   1.10643166]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -0.74866447]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.41231994]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
   0.84432121]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   0.32472465]]


In [29]:
print(X_test)

[[-0.95692675  1.62776996 -0.57427105 ...  0.66011376  0.97628121
   1.62185911]
 [ 1.04501206 -0.61433742 -0.57427105 ...  0.66011376 -1.02429504
   0.504204  ]
 [-0.95692675 -0.61433742  1.74133801 ...  0.66011376  0.97628121
  -0.41865644]
 ...
 [-0.95692675 -0.61433742  1.74133801 ...  0.66011376 -1.02429504
   0.72775202]
 [-0.95692675  1.62776996 -0.57427105 ...  0.66011376  0.97628121
  -1.54162886]
 [-0.95692675  1.62776996 -0.57427105 ...  0.66011376 -1.02429504
   1.62356528]]


In [30]:
#Part:2  : Building the ANN
#Initializing the ANN
ann=tf.keras.models.Sequential()

In [31]:
#Adding the input layer and the first hiddden layer
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [32]:
#Adding the input layer and the second hiddden layer
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [33]:
#output layer
ann.add(tf.keras.layers.Dense(units=1,activation='relu'))

In [39]:
#PART 3 Training the ANN
#compiling the ANN
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics="accuracy")


In [40]:
#Trainingthe ANN on the Training set
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 2.2635 - accuracy: 0.7344
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 1.8293 - accuracy: 0.7662
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 1.6890 - accuracy: 0.7722
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 1.6280 - accuracy: 0.7708
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 1.2243 - accuracy: 0.7696
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.8403 - accuracy: 0.7635
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.6496 - accuracy: 0.7706
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.5997 - accuracy: 0.7750
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.5841 - accuracy: 0.7772
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.5677 - accura

In [48]:
#Part 4 :Predict the model and evaluate the model
#Query :France,600,male,40age,3y,60000,2,yes,yes,50000
#should customer leave the bank
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])) >0.5)

[[False]]


In [56]:
#Predict the Test set results
y_pred=ann.predict(X_test)
y_pred=(y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [57]:
#Making the confusion matrix
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1536   59]
 [ 218  187]]


0.8615